//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneBS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAP()
        {
            this.FAVORI = new HashSet<FAVORI>();
            this.YORUM = new HashSet<YORUM>();
            this.KUTUPHANE = new HashSet<KUTUPHANE>();
        }
    
        public int Kitap_ID { get; set; }
        public string Kitap_Adi { get; set; }
        public string Kitap_Turu { get; set; }
        public string Kitap_Yazari { get; set; }
        public string Kitap_YayinEvi { get; set; }
        public string Kitap_TedarikciTuru { get; set; }
        public string Kitap_Alinabilirlik { get; set; }
        public int Tarih_ID { get; set; }
        public int Uye_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORI> FAVORI { get; set; }
        public virtual TARIH TARIH { get; set; }
        public virtual UYE UYE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YORUM> YORUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KUTUPHANE> KUTUPHANE { get; set; }
    }
}
