//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneBS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUTUPHANE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KUTUPHANE()
        {
            this.KITAP = new HashSet<KITAP>();
            this.ISTEK = new HashSet<ISTEK>();
        }
    
        public int Kutuphane_ID { get; set; }
        public string Kutuphane_Adi { get; set; }
        public string Kutuphane_Adres { get; set; }
        public string Kutuphane_Telefon { get; set; }
        public string Kutuphane_Websitesi { get; set; }
        public string Kutuphane_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KITAP> KITAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISTEK> ISTEK { get; set; }
    }
}
