//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneBS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TARIH()
        {
            this.KITAP = new HashSet<KITAP>();
        }
    
        public int Tarih_ID { get; set; }
        public System.DateTime Tarih_OduncTarihi { get; set; }
        public System.DateTime Tarih_TeslimTarihi { get; set; }
        public System.DateTime Tarih_TeslimAlinan { get; set; }
        public Nullable<int> Tarih_Gecikme { get; set; }
        public Nullable<int> Ceza_ID { get; set; }
    
        public virtual CEZA CEZA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KITAP> KITAP { get; set; }
    }
}
