//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneBS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YORUM
    {
        public int Yorum_ID { get; set; }
        public int Kitap_ID { get; set; }
        public int Uye_ID { get; set; }
        public string Yorum_Icerik { get; set; }
        public System.DateTime Yorum_Tarih { get; set; }
    
        public virtual KITAP KITAP { get; set; }
        public virtual UYE UYE { get; set; }
    }
}
